/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tabla_alumno;

import conexion.Sql;
import javax.swing.JOptionPane;
import conexion.Config;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author hp
 */
public class VentanaAcceso extends javax.swing.JFrame {
    public static int guardaOption = 0;
    public static String seleccion = "";

    private Alumno sel;

    public VentanaAcceso() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Alumnos");
        setResizable(true);  
        llenarTabla(); 
       
    }
    
        private void llenarTabla() {
        String buscar = txtBuscar.getText().trim();
        ArrayList<Alumno> lista;
        if (buscar.length() == 0 ) {
            lista = Sql.mostrar();
            
        } else {
            lista = Sql.mostrar(buscar);
            
            
        }
        String titulos[] = {"#", "Num_control", "Nombre", "Apellido", "FechaNac", "Sexo", "Carrera"};
        DefaultTableModel t = new DefaultTableModel();
        int x = 0;
        Object elementos[][] = new Object[lista.size()][8];
        for (Alumno sel : lista) {
            elementos[x][0] = (x + 1) + "";
            elementos[x][1] = sel.getNumcontrol();
            elementos[x][2] = sel.getNombre();
            elementos[x][3] = sel.getApellido();
            elementos[x][4] = sel.getFecnac();
            elementos[x][5] = sel.getSexo();
            elementos[x][6] = sel.getCarrera();
            x++;
        }
        t.setDataVector(elementos, titulos);
        tabla.setModel(t);
        Config.configTabla(tabla, 0, 30);
        Config.configTabla(tabla, 1, 80);
        Config.configTabla(tabla, 2, 80);
        Config.configTabla(tabla, 3, 80);
        Config.configTabla(tabla, 4, 80);
        Config.configTabla(tabla, 5, 80);
        
    }

    private void creaRegistro() {
        valida();
        sel = new Alumno();
        sel.setNumcontrol(Integer.parseInt(matricula.getText()));
        sel.setNombre(nombre.getText());
        sel.setApellido(apellido.getText());
        sel.setFecnac(fecha.getText());
        sel.setSexo(sexo.getSelectedItem() + "");
        sel.setCarrera(carrera.getSelectedItem() + "");
        
        
    }
    private String valida() {
        String msj = "";
        msj += (!matricula.getText().matches("[1-90 ]+")) ? "Se requiere un numero de control valido\n" : "";
        return msj;
    }
        private void seleccionar() {
        int s = -1;
        s = tabla.getSelectedRow();
        if (s > -1) {
            seleccion = tabla.getValueAt(s, 1).toString();
        }
    }
    private void llenarCampos() {
        sel = Sql.getAlumno(seleccion);
        if (sel == null) {
            JOptionPane.showMessageDialog(this, "Error");
            dispose();
        }
        matricula.setText(sel.getNumcontrol() + "");
        nombre.setText(sel.getNombre());
        apellido.setText(sel.getApellido());
        fecha.setText(sel.getFecnac());

    }

    private void eliminar() {
        if (seleccion.length() > 0) {
            if (Sql.eliminar(seleccion)) { 
                llenarTabla();
            } else {
                JOptionPane.showMessageDialog(this, "Error al eliminar el registro");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Seleccione un elemento");
        }
    }
    private void vaciarCampos (){
        matricula.setText("");
        nombre.setText("");
        apellido.setText("");
        fecha.setText("");
        sexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Hombre", "Mujer" }));
        carrera.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Ingenieria civil", "Ingenieria en gestion", "Ingenieria en sistemas" }));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        matricula = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        apellido = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        sexo = new javax.swing.JComboBox<>();
        carrera = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        fecha = new javax.swing.JTextField();
        actualizar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jbBuscar = new javax.swing.JButton();
        txtBuscar = new javax.swing.JTextField();
        editar = new javax.swing.JButton();
        eliminar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        restablece = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Número de control");

        jLabel2.setText("Nombre");

        jLabel5.setText("Sexo");

        sexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Hombre", "Mujer" }));
        sexo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        carrera.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Ingenieria civil", "Ingenieria en gestion", "Ingenieria en sistemas" }));

        jLabel6.setText("Carrera");

        jLabel7.setText("Fecha de nacimiento");

        actualizar.setText("Actualizar");
        actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarActionPerformed(evt);
            }
        });

        jLabel9.setText("Apellido");

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tabla);

        jbBuscar.setText("Buscar");
        jbBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarActionPerformed(evt);
            }
        });

        editar.setText("Editar");
        editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarActionPerformed(evt);
            }
        });

        eliminar.setText("Eliminar");
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });

        jLabel8.setText("YYYY-MM-DD");

        restablece.setText("Restablecer Tabla");
        restablece.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restableceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel7))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel8))
                                    .addComponent(sexo, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(carrera, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(actualizar))
                                    .addComponent(matricula, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(nombre, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(apellido, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbBuscar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(restablece))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addComponent(editar, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65)
                        .addComponent(eliminar)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(matricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(sexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(carrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(actualizar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbBuscar)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(restablece))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editar)
                    .addComponent(eliminar))
                .addGap(75, 75, 75))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarActionPerformed
        // TODO add your handling code here:
        String msj = valida();
        if (msj.length() > 0) {
            JOptionPane.showMessageDialog(this, msj);
        } else {
            creaRegistro();
            if (guardaOption == 0) {
                if (Sql.agregar(sel)) {
                    llenarTabla();
                    vaciarCampos();
                } else {
                    JOptionPane.showMessageDialog(this, "Todos los campos son necesarios");
                }
            }
            if (guardaOption == 1) {
                if (Sql.editar(sel, seleccion)) {
                    guardaOption = 0;
                    llenarTabla();
                    vaciarCampos();
                    seleccion = "";
                } else {
                    JOptionPane.showMessageDialog(this, "Revise los campos");
                }
            }
        }
    }//GEN-LAST:event_actualizarActionPerformed

    private void jbBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarActionPerformed
        // TODO add your handling code here:
        llenarTabla();
    }//GEN-LAST:event_jbBuscarActionPerformed

    private void editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarActionPerformed
        // TODO add your handling code here: 
        seleccionar();
        if (seleccion.length() > 0) {
            guardaOption = 1;
            //new GestionAlumno(this, true);
            llenarCampos();   
        } else {
            JOptionPane.showMessageDialog(this, "Seleccione un elemento");
        }
    }//GEN-LAST:event_editarActionPerformed

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
        // TODO add your handling code here:
        seleccionar();
        int respConf = 0;
        if ("".equals(seleccion)) {
            JOptionPane.showMessageDialog(this, "Seleccione un elemento");
        } else {
            respConf = JOptionPane.showConfirmDialog(this, "¿Eliminar el registro?");
            if (respConf == 0) {
                eliminar();
            }
        }
        
    }//GEN-LAST:event_eliminarActionPerformed

    private void restableceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restableceActionPerformed
        // TODO add your handling code here:
        txtBuscar.setText("");
        llenarTabla();
    }//GEN-LAST:event_restableceActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actualizar;
    private javax.swing.JTextField apellido;
    private javax.swing.JComboBox<String> carrera;
    private javax.swing.JButton editar;
    private javax.swing.JButton eliminar;
    private javax.swing.JTextField fecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbBuscar;
    private javax.swing.JTextField matricula;
    private javax.swing.JTextField nombre;
    private javax.swing.JButton restablece;
    private javax.swing.JComboBox<String> sexo;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
